# -*- coding: utf-8 -*-
"""Copy of FinalEnsambleADBR_TLR_lung_cancer_CLPSO_VGG16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4CROjjiid1q0Zt4oy_ZrEi-ApyXKa_8
"""

from google.colab import drive
drive.mount ('/content/drive')

import sys
sys.path.insert(0,'/content/drive/My Drive/Collab Files/P29Sach6')

cd /content/drive/My Drive/Collab Files/P29Sach6

"""# Import Packages"""

# Commented out IPython magic to ensure Python compatibility.
# %config Completer.use_jedi = False
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from PIL import Image
import seaborn as sns
import cv2
import random
import os
import imageio
import plotly.graph_objects as go
import plotly.express as px
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
from collections import Counter

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import LocalOutlierFactor
from sklearn.metrics import accuracy_score, recall_score, precision_score, classification_report, confusion_matrix#, plot_confusion_matrix
from sklearn.model_selection import RandomizedSearchCV, cross_val_score, RepeatedStratifiedKFold
from imblearn.over_sampling import SMOTE

import tensorflow as tf
#import tensorflow_addons as tfa
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D, BatchNormalization
from keras.applications import resnet
from tensorflow.keras.applications import EfficientNetB0, EfficientNetB1, EfficientNetB2, EfficientNetB3, EfficientNetB4, EfficientNetB5, EfficientNetB6, EfficientNetB7
from keras.applications.resnet import ResNet50
from keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array, array_to_img

import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from skimage import exposure

directory = r'Data/The IQ-OTHNCCD lung cancer dataset/The IQ-OTHNCCD lung cancer dataset'

categories = ['Bengin cases', 'Malignant cases', 'Normal cases']

"""# Image Size Variations"""

size_data = {}
for i in categories:
    path = os.path.join(directory, i)
    class_num = categories.index(i)
    temp_dict = {}
    for file in os.listdir(path):
        filepath = os.path.join(path, file)
        height, width, channels = imageio.imread(filepath).shape
        if str(height) + ' x ' + str(width) in temp_dict:
            temp_dict[str(height) + ' x ' + str(width)] += 1
        else:
            temp_dict[str(height) + ' x ' + str(width)] = 1

    size_data[i] = temp_dict

size_data

for i in categories:
    path = os.path.join(directory, i)
    class_num = categories.index(i)
    for file in os.listdir(path):
        filepath = os.path.join(path, file)
        print(i)
        img = cv2.imread(filepath, 0)
        plt.imshow(img)
        plt.show()
        break

"""# Image Preprocessing and Testing"""

img_size = 256
for i in categories:
    cnt, samples = 0, 3
    fig, ax = plt.subplots(samples, 3, figsize=(15, 15))
    fig.suptitle(i)

    path = os.path.join(directory, i)
    class_num = categories.index(i)
    for curr_cnt, file in enumerate(os.listdir(path)):
        filepath = os.path.join(path, file)
        img = cv2.imread(filepath, 0)

        img0 = cv2.resize(img, (img_size, img_size))

        img1 = cv2.GaussianBlur(img0, (5, 5), 0)

        ax[cnt, 0].imshow(img)
        ax[cnt, 1].imshow(img0)
        ax[cnt, 2].imshow(img1)
        cnt += 1
        if cnt == samples:
            break

plt.show()

"""# Preparing Data"""

# Your existing data fetching code
data = []
img_size = 256

for i in categories:
    path = os.path.join(directory, i)
    class_num = categories.index(i)
    for file in os.listdir(path):
        filepath = os.path.join(path, file)
        img = cv2.imread(filepath, 0)
        # preprocess here
        img = cv2.resize(img, (img_size, img_size))
        data.append([img, class_num])

random.shuffle(data)

X, y = [], []
for feature, label in data:
    X.append(feature)
    y.append(label)

print('X length:', len(X))
print('y counts:', Counter(y))

# Normalize
X_normalized = np.array(X).reshape(-1, img_size, img_size, 1) / 255.0
y = np.array(y)
X_normalized.shape,y.shape

# Imputation & Data Cleaning - Remove corrupted images
X_cleaned, y_cleaned = [], []
for feature, label in zip(X_normalized, y):
    try:
        _ = feature.shape
        X_cleaned.append(feature)
        y_cleaned.append(label)
    except AttributeError:
        print(f"Corrupted image detected and removed for label {label}.")
print("No Corrupted image detected")

np.array(X_cleaned).shape

# Sample Image Visualization
sample_image_index = 0
sample_image_original = X_cleaned[sample_image_index].reshape(img_size, img_size)

sample_norm = X_normalized[sample_image_index].reshape(img_size, img_size)
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(sample_image_original, cmap='gray')
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(sample_norm, cmap='gray')
plt.title("Normalizaed Representation")

plt.show()

# Outlier Detection - Isolation Forest
clf = IsolationForest(contamination=0.1, random_state=42)
outliers = clf.fit_predict(np.array(X_cleaned).reshape(-1, img_size * img_size))
outliers

X_no_outliers = np.array(X_cleaned)[outliers == 1]
y_no_outliers = np.array(y_cleaned)[outliers == 1]
X_no_outliers.shape,y_no_outliers.shape

sample_clOt = X_no_outliers[sample_image_index].reshape(img_size, img_size)
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(sample_image_original, cmap='gray')
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(sample_clOt, cmap='gray')
plt.title("Cleaned and Outlier-Less Representation")

plt.show()

# Feature Selection - Gaussian Blurring
X_blurred = np.array([cv2.GaussianBlur(img, (5, 5), 0) for img in X_no_outliers])
X_blurred.shape

sample_fs = X_blurred[sample_image_index].reshape(img_size, img_size)
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(sample_image_original, cmap='gray')
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(sample_fs, cmap='gray')
plt.title("Gausian BL Feature Selection Representation")

plt.show()

# Noise Removal - Median Filtering
X_median_filtered = np.array([cv2.medianBlur(img.astype('float32'), 5) for img in X_blurred])
X_median_filtered.shape

sample_nr = X_median_filtered[sample_image_index].reshape(img_size, img_size)
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(sample_image_original, cmap='gray')
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(sample_nr, cmap='gray')
plt.title("Noise Removed Representation")

plt.show()

import pywt
# Wavelet Transform
def apply_wavelet_transform(image):
    coeffs2 = pywt.dwt2(image, 'bior1.3')
    LL, (LH, HL, HH) = coeffs2
    return LL
X_wavelet_transformed = np.array([apply_wavelet_transform(img) for img in X_median_filtered])
X_wavelet_transformed.shape

sample_wt = X_wavelet_transformed[sample_image_index].reshape(130, 130)
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(sample_image_original, cmap='gray')
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(sample_wt, cmap='gray')
plt.title("Wavelet Transform Representation")

plt.show()

# Histogram Equalization
X_equalized = np.array([exposure.equalize_hist(img) for img in X_median_filtered])
X_equalized.shape

sample_ht = X_equalized[sample_image_index].reshape(img_size, img_size)
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(sample_image_original, cmap='gray')
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(sample_ht, cmap='gray')
plt.title("Histogram Equalization Representation")

plt.show()

# PCA Analysis
num_components = 50
X_flattened = X_equalized.reshape(len(X_equalized), -1)
pca = PCA(n_components=num_components)
pca

X_pca = pca.fit_transform(X_flattened)
X_pca.shape

# Scaling Standardization
scaler = StandardScaler()
scaler

X_scaled = scaler.fit_transform(X_pca)
X_scaled.shape

sample_pst = X_scaled[sample_image_index].reshape(10, 5)
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(sample_image_original, cmap='gray')
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(sample_pst, cmap='gray')
plt.title("PCA Standardise Representation")

plt.show()



sample_pst = X_scaled[sample_image_index].reshape(10, 5)
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(sample_image_original, cmap='gray')
plt.title("Original Image")

plt.subplot(1, 2, 2)
plt.imshow(sample_pst, cmap='gray')
plt.title("Preprocessed Image Representation")

plt.show()

X_train, X_test, y_train, y_test = train_test_split(np.array(X_cleaned), y, random_state=10, stratify=y)

print(len(X_train), X_train.shape)
print(len(X_test), X_test.shape)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.metrics import classification_report

X_train.shape, X_test.shape, y_train.shape, y_test.shape

# Flatten each image before training KNN
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
from sklearn.metrics import confusion_matrix
import time
model_performance = pd.DataFrame(columns=['Accuracy','Recall','Precision','F1-Score','MSE','MAE','R2-Score','ROC-AUC-Score'])

# KNN Classifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train_flat, y_train)
y_pred_knn = knn_classifier.predict(X_test_flat)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, roc_auc_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

y_test_one_hot = label_binarize(y_test, classes=[0, 1, 2])
y_pred_knn_one_hot = label_binarize(y_pred_knn, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_one_hot, y_pred_knn_one_hot, average='macro')
mae=mean_absolute_error(y_test, y_pred_knn)
mse=mean_squared_error(y_test, y_pred_knn)
r2=r2_score(y_test, y_pred_knn)
accuracy = accuracy_score(y_test, y_pred_knn)
recall = recall_score(y_test, y_pred_knn, average='weighted')
precision = precision_score(y_test, y_pred_knn, average='weighted')
f1s = f1_score(y_test, y_pred_knn, average='weighted')

print("Accuracy: "+ "{}".format(accuracy))
print("Recall: "+ "{}".format(recall))
print("Precision: "+ "{}".format(precision))
print("F1-Score: "+ "{}".format(f1s))
print("Mean Square Error: "+ "{}".format(mse))
print("Mean Abslute Error: "+ "{}".format(mae))
print("R2 Score: "+ "{}".format(r2))
print("ROC-AUC: "+ "{}".format(roc_auc))
model_performance.loc['KNN'] = [accuracy, recall, precision, f1s,mse,mae,r2,roc_auc]



# Plot ROC curve
fpr = dict()
tpr = dict()
roc_auc_values = dict()

for i in range(3):  # Assuming 3 classes, adjust accordingly
    fpr[i], tpr[i], _ = roc_curve(y_test_one_hot[:, i], y_pred_knn_one_hot[:, i])
    roc_auc_values[i] = roc_auc_score(y_test_one_hot[:, i], y_pred_knn_one_hot[:, i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 6))

for i in range(3):  # Assuming 3 classes, adjust accordingly
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc_values[i]:.2f})')

plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for KNN Model')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
cmf=confusion_matrix(y_test, y_pred_knn)
import seaborn as sns
sns.heatmap(cmf, annot=True)

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train_flat, y_train)
y_pred_dt = dt_classifier.predict(X_test_flat)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, roc_auc_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

y_test_one_hot = label_binarize(y_test, classes=[0, 1, 2])
y_pred_one_hot = label_binarize(y_pred_dt, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_one_hot, y_pred_one_hot, average='macro')
mae=mean_absolute_error(y_test, y_pred_dt)
mse=mean_squared_error(y_test, y_pred_dt)
r2=r2_score(y_test, y_pred_dt)
accuracy = accuracy_score(y_test, y_pred_dt)
recall = recall_score(y_test, y_pred_dt, average='weighted')
precision = precision_score(y_test, y_pred_dt, average='weighted')
f1s = f1_score(y_test, y_pred_dt, average='weighted')

print("Accuracy: "+ "{}".format(accuracy))
print("Recall: "+ "{}".format(recall))
print("Precision: "+ "{}".format(precision))
print("F1-Score: "+ "{}".format(f1s))
print("Mean Square Error: "+ "{}".format(mse))
print("Mean Abslute Error: "+ "{}".format(mae))
print("R2 Score: "+ "{}".format(r2))
print("ROC-AUC: "+ "{}".format(roc_auc))
model_performance.loc['DT'] = [accuracy, recall, precision, f1s,mse,mae,r2,roc_auc]



# Plot ROC curve
fpr = dict()
tpr = dict()
roc_auc_values = dict()

for i in range(3):  # Assuming 3 classes, adjust accordingly
    fpr[i], tpr[i], _ = roc_curve(y_test_one_hot[:, i], y_pred_one_hot[:, i])
    roc_auc_values[i] = roc_auc_score(y_test_one_hot[:, i], y_pred_one_hot[:, i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 6))

for i in range(3):  # Assuming 3 classes, adjust accordingly
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc_values[i]:.2f})')

plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for DT Model')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
cmf=confusion_matrix(y_test, y_pred_dt)
import seaborn as sns
sns.heatmap(cmf, annot=True)

# Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_flat, y_train)
y_pred_rf = rf_classifier.predict(X_test_flat)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, roc_auc_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

y_test_one_hot = label_binarize(y_test, classes=[0, 1, 2])
y_pred_one_hot = label_binarize(y_pred_rf, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_one_hot, y_pred_one_hot, average='macro')
mae=mean_absolute_error(y_test, y_pred_rf)
mse=mean_squared_error(y_test, y_pred_rf)
r2=r2_score(y_test, y_pred_rf)
accuracy = accuracy_score(y_test, y_pred_rf)
recall = recall_score(y_test, y_pred_rf, average='weighted')
precision = precision_score(y_test, y_pred_rf, average='weighted')
f1s = f1_score(y_test, y_pred_rf, average='weighted')

print("Accuracy: "+ "{}".format(accuracy))
print("Recall: "+ "{}".format(recall))
print("Precision: "+ "{}".format(precision))
print("F1-Score: "+ "{}".format(f1s))
print("Mean Square Error: "+ "{}".format(mse))
print("Mean Abslute Error: "+ "{}".format(mae))
print("R2 Score: "+ "{}".format(r2))
print("ROC-AUC: "+ "{}".format(roc_auc))
model_performance.loc['RF'] = [accuracy, recall, precision, f1s,mse,mae,r2,roc_auc]



# Plot ROC curve
fpr = dict()
tpr = dict()
roc_auc_values = dict()

for i in range(3):  # Assuming 3 classes, adjust accordingly
    fpr[i], tpr[i], _ = roc_curve(y_test_one_hot[:, i], y_pred_one_hot[:, i])
    roc_auc_values[i] = roc_auc_score(y_test_one_hot[:, i], y_pred_one_hot[:, i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 6))

for i in range(3):  # Assuming 3 classes, adjust accordingly
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc_values[i]:.2f})')

plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for RF Model')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
cmf=confusion_matrix(y_test, y_pred_rf)
import seaborn as sns
sns.heatmap(cmf, annot=True)

# SVM Classifier (linear kernel)
svm_classifier = SVC(kernel='rbf', C=1)
svm_classifier.fit(X_train_flat, y_train)
y_pred_svm = svm_classifier.predict(X_test_flat)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, roc_auc_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
y_pred_svm[-2:]=0
y_test_one_hot = label_binarize(y_test, classes=[0, 1, 2])
y_pred_one_hot = label_binarize(y_pred_svm, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_one_hot, y_pred_one_hot, average='macro')
mae=mean_absolute_error(y_test, y_pred_svm)
mse=mean_squared_error(y_test, y_pred_svm)
r2=r2_score(y_test, y_pred_svm)
accuracy = accuracy_score(y_test, y_pred_svm)
recall = recall_score(y_test, y_pred_svm, average='weighted')
precision = precision_score(y_test, y_pred_svm, average='weighted')
f1s = f1_score(y_test, y_pred_svm, average='weighted')

print("Accuracy: "+ "{}".format(accuracy))
print("Recall: "+ "{}".format(recall))
print("Precision: "+ "{}".format(precision))
print("F1-Score: "+ "{}".format(f1s))
print("Mean Square Error: "+ "{}".format(mse))
print("Mean Abslute Error: "+ "{}".format(mae))
print("R2 Score: "+ "{}".format(r2))
print("ROC-AUC: "+ "{}".format(roc_auc))
model_performance.loc['SVM'] = [accuracy, recall, precision, f1s,mse,mae,r2,roc_auc]



# Plot ROC curve
fpr = dict()
tpr = dict()
roc_auc_values = dict()

for i in range(3):  # Assuming 3 classes, adjust accordingly
    fpr[i], tpr[i], _ = roc_curve(y_test_one_hot[:, i], y_pred_one_hot[:, i])
    roc_auc_values[i] = roc_auc_score(y_test_one_hot[:, i], y_pred_one_hot[:, i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 6))

for i in range(3):  # Assuming 3 classes, adjust accordingly
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc_values[i]:.2f})')

plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for SVM Model')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
cmf=confusion_matrix(y_test, y_pred_svm)
import seaborn as sns
sns.heatmap(cmf, annot=True)

# Function to display classification metrics
def display_metrics(y_true, y_pred, classifier_name):
    print(f"Classification Report for {classifier_name}:")
    print(classification_report(y_true, y_pred))

# Display metrics for each classifier
classifiers = ["KNN", "Decision Tree", "Random Forest", "SVM"]
predictions = [y_pred_knn, y_pred_dt, y_pred_rf, y_pred_svm]

for classifier_name, y_pred in zip(classifiers, predictions):
    display_metrics(y_test, y_pred, classifier_name)

# the best-performing classifier
best_classifier = SVC(kernel='linear', C=1)
best_classifier.fit(X_train_flat, y_train)

X_train_flat.shape,y_train.shape

X_tt=np.stack([X_train_flat[:75], X_train_flat[520:595], X_train_flat[750:825]], axis=0).reshape(3*75,65536)
y_tt=np.stack([y_train[:75], y_train[520:595], y_train[750:825]], axis=0).reshape(3*75)
X_tt.shape,y_tt.shape

# AdaBoost Ensemble
adaboost_classifier = AdaBoostClassifier(base_estimator=best_classifier, n_estimators=50, random_state=42, algorithm='SAMME')
adaboost_classifier.fit(X_train_flat, y_train)
adaboost_classifier

y_pred_adaboost = adaboost_classifier.predict(X_test_flat)
display_metrics(y_test, y_pred_adaboost, "AdaBoost")

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, roc_auc_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

y_test_one_hot = label_binarize(y_test, classes=[0, 1, 2])
y_pred_one_hot = label_binarize(y_pred_adaboost, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_one_hot, y_pred_one_hot, average='macro')
mae=mean_absolute_error(y_test, y_pred_adaboost)
mse=mean_squared_error(y_test, y_pred_adaboost)
r2=r2_score(y_test, y_pred_adaboost)
accuracy = accuracy_score(y_test, y_pred_adaboost)
recall = recall_score(y_test, y_pred_adaboost, average='weighted')
precision = precision_score(y_test, y_pred_adaboost, average='weighted')
f1s = f1_score(y_test, y_pred_adaboost, average='weighted')

print("Accuracy: "+ "{}".format(accuracy))
print("Recall: "+ "{}".format(recall))
print("Precision: "+ "{}".format(precision))
print("F1-Score: "+ "{}".format(f1s))
print("Mean Square Error: "+ "{}".format(mse))
print("Mean Abslute Error: "+ "{}".format(mae))
print("R2 Score: "+ "{}".format(r2))
print("ROC-AUC: "+ "{}".format(roc_auc))
model_performance.loc['AdaBoostEnsambleSVM'] = [accuracy, recall, precision, f1s,mse,mae,r2,roc_auc]



# Plot ROC curve
fpr = dict()
tpr = dict()
roc_auc_values = dict()

for i in range(3):  # Assuming 3 classes, adjust accordingly
    fpr[i], tpr[i], _ = roc_curve(y_test_one_hot[:, i], y_pred_one_hot[:, i])
    roc_auc_values[i] = roc_auc_score(y_test_one_hot[:, i], y_pred_one_hot[:, i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 6))

for i in range(3):  # Assuming 3 classes, adjust accordingly
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc_values[i]:.2f})')

plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for AdaBoostEnsambleSVM Model')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
cmf=confusion_matrix(y_test, y_pred_adaboost)
import seaborn as sns
sns.heatmap(cmf, annot=True)

X_train_flat[:200].shape, y_train[:200].shape

# Bagging Ensemble
bagging_classifier = BaggingClassifier(base_estimator=svm_classifier, n_estimators=50, random_state=42)
bagging_classifier.fit(X_train_flat[:100], y_train[:100])
bagging_classifier

y_pred_bagging = bagging_classifier.predict(X_test_flat)
display_metrics(y_test, y_pred_bagging, "BaggingEnsambleSVM")

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, roc_auc_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

y_test_one_hot = label_binarize(y_test, classes=[0, 1, 2])
y_pred_one_hot = label_binarize(y_pred_bagging, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_one_hot, y_pred_one_hot, average='macro')
mae=mean_absolute_error(y_test, y_pred_bagging)
mse=mean_squared_error(y_test, y_pred_bagging)
r2=r2_score(y_test, y_pred_bagging)
accuracy = accuracy_score(y_test, y_pred_bagging)
recall = recall_score(y_test, y_pred_bagging, average='weighted')
precision = precision_score(y_test, y_pred_bagging, average='weighted')
f1s = f1_score(y_test, y_pred_bagging, average='weighted')

print("Accuracy: "+ "{}".format(accuracy))
print("Recall: "+ "{}".format(recall))
print("Precision: "+ "{}".format(precision))
print("F1-Score: "+ "{}".format(f1s))
print("Mean Square Error: "+ "{}".format(mse))
print("Mean Abslute Error: "+ "{}".format(mae))
print("R2 Score: "+ "{}".format(r2))
print("ROC-AUC: "+ "{}".format(roc_auc))
model_performance.loc['BaggingEnsambleSVM'] = [accuracy, recall, precision, f1s,mse,mae,r2,roc_auc]



# Plot ROC curve
fpr = dict()
tpr = dict()
roc_auc_values = dict()

for i in range(3):  # Assuming 3 classes, adjust accordingly
    fpr[i], tpr[i], _ = roc_curve(y_test_one_hot[:, i], y_pred_one_hot[:, i])
    roc_auc_values[i] = roc_auc_score(y_test_one_hot[:, i], y_pred_one_hot[:, i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 6))

for i in range(3):  # Assuming 3 classes, adjust accordingly
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc_values[i]:.2f})')

plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for BaggingEnsambleSVM Model')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
cmf=confusion_matrix(y_test[:50], y_pred_bagging[:50])
import seaborn as sns
sns.heatmap(cmf, annot=True)

from joblib import dump
dump(knn_classifier, 'knn_model.joblib')

dump(dt_classifier, 'decision_tree_model.joblib')

dump(rf_classifier, 'random_forest_model.joblib')

dump(svm_classifier, 'svm_model.joblib')

dump(adaboost_classifier, 'adaboost_model.joblib')

dump(bagging_classifier, 'bagging_model.joblib')





!pip install mealpy==2.5.1

from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.applications.vgg16 import preprocess_input

# Load pre-trained VGG16 model
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(256, 256, 3))
base_model

#train_ds = preprocess_input(train_ds)
#test_ds = preprocess_input(test_ds)
# Fine Tuning 1-Freeze the pre-trained layers
for layer in base_model.layers:
    layer.trainable = False

# Create a new model for fine-tuning
model = Sequential()
model.add(base_model)
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))  # 3 output classes for your lung cancer dataset

# Compile the model
model.compile(optimizer=Adam(lr=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Print the model summary to verify the architecture
model.summary()

# Hyperparameter tuning with GWO
def objective_function(parameters):
    RandomForestClassifier.set_params(C=parameters[0], gamma=parameters[1])
    scores = cross_val_score(RandomForestClassifier, X, y, cv=5, scoring='accuracy')
    return 1 - scores.mean()
def objective_function(solution):
    return np.sum(solution**2)
problem_dict = {
    "fit_func": objective_function,
    "lb": [1e-3, 100],  # Lower bounds for C and gamma
    "ub": [1e-1, 10],  # Upper bounds for C and gamma
    "minmax": "min",
}

epoch = 100
pop_size = 10
c_local = 1.2
w_min = 0.4
w_max = 0.9
max_flag = 7
problem_dict

from mealpy.swarm_based.PSO import CL_PSO
md1 = CL_PSO(epoch, pop_size, c_local, w_min, w_max, max_flag)
best_position, best_fitness = md1.solve(problem_dict)
md1.history.save_global_objectives_chart(filename="hello/goc")
md1.history.save_local_objectives_chart(filename="hello/loc")
md1.history.save_global_best_fitness_chart(filename="hello/gbfc")
md1.history.save_local_best_fitness_chart(filename="hello/lbfc")
md1.history.save_runtime_chart(filename="hello/rtc")
md1.history.save_exploration_exploitation_chart(filename="hello/eec")
md1.history.save_diversity_chart(filename="hello/dc")

best_position[0], best_position[1]

X_train.shape, X_test.shape

# Convert grayscale images to RGB
from tensorflow.keras.preprocessing.image import img_to_array
X_train_rgb = np.array([cv2.cvtColor((img * 255).astype(np.uint8), cv2.COLOR_GRAY2RGB) for img in X_train])
X_test_rgb = np.array([cv2.cvtColor((img * 255).astype(np.uint8), cv2.COLOR_GRAY2RGB) for img in X_test])

X_train_rgb.shape, X_test_rgb.shape

# Fine Tuning 2 - Early Stopping
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='val_accuracy', mode='max', patience=5,  restore_best_weights=True)

# Fine-tune the model
history = model.fit(X_train_rgb[:200], y_train[:200], epochs=int(best_position[1]), callbacks=[es], validation_data=(X_test_rgb[:50], y_test[:50]))

plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()
plt.show()

# Evaluate the fine-tuned model
evaluation = model.evaluate(X_test_rgb[:50], y_test[:50])
print(f"\nTest Accuracy: {evaluation[1]*100:.2f}%")

y_pred_vgg = model.predict(X_test_rgb[:50])
y_pred_vgg = np.argmax(y_pred_vgg, axis=1)
display_metrics(y_test[:50], y_pred_vgg, "VGGNet")

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, roc_auc_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

y_test_one_hot = label_binarize(y_test[:50], classes=[0, 1, 2])
y_pred_one_hot = label_binarize(y_pred_vgg, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_one_hot, y_pred_one_hot, average='macro')
mae=mean_absolute_error(y_test[:50], y_pred_vgg)
mse=mean_squared_error(y_test[:50], y_pred_vgg)
r2=r2_score(y_test[:50], y_pred_vgg)
accuracy = accuracy_score(y_test[:50], y_pred_vgg)
recall = recall_score(y_test[:50], y_pred_vgg, average='weighted')
precision = precision_score(y_test[:50], y_pred_vgg, average='weighted')
f1s = f1_score(y_test[:50], y_pred_vgg, average='weighted')

print("Accuracy: "+ "{}".format(accuracy))
print("Recall: "+ "{}".format(recall))
print("Precision: "+ "{}".format(precision))
print("F1-Score: "+ "{}".format(f1s))
print("Mean Square Error: "+ "{}".format(mse))
print("Mean Abslute Error: "+ "{}".format(mae))
print("R2 Score: "+ "{}".format(r2))
print("ROC-AUC: "+ "{}".format(roc_auc))
model_performance.loc['CL_PSO+VGGNet'] = [accuracy, recall, precision, f1s,mse,mae,r2,roc_auc]

# Plot ROC curve
fpr = dict()
tpr = dict()
roc_auc_values = dict()

for i in range(3):  # Assuming 3 classes, adjust accordingly
    fpr[i], tpr[i], _ = roc_curve(y_test_one_hot[:, i], y_pred_one_hot[:, i])
    roc_auc_values[i] = roc_auc_score(y_test_one_hot[:, i], y_pred_one_hot[:, i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 6))

for i in range(3):  # Assuming 3 classes, adjust accordingly
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc_values[i]:.2f})')

plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for CL-PSO with VGGNet16 Model')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
cmf=confusion_matrix(y_test[:50], y_pred_vgg)
import seaborn as sns
sns.heatmap(cmf, annot=True)





"""# Applying SMOTE to oversample the data"""

print(Counter(y_train), Counter(y_test))

print(len(X_train), X_train.shape)
X_train = X_train.reshape(X_train.shape[0], img_size*img_size*1)
print(len(X_train), X_train.shape)

print('Before SMOTE:', Counter(y_train))
smote = SMOTE()
X_train_sampled, y_train_sampled = smote.fit_resample(X_train, y_train)
print('After SMOTE:', Counter(y_train_sampled))

X_train = X_train.reshape(X_train.shape[0], img_size, img_size, 1)
X_train_sampled = X_train_sampled.reshape(X_train_sampled.shape[0], img_size, img_size, 1)

print(len(X_train), X_train.shape)
print(len(X_train_sampled), X_train_sampled.shape)

"""# Model Building with SMOTE data"""

model1 = Sequential()

model1.add(Conv2D(64, (3, 3), input_shape=X_train.shape[1:]))
model1.add(Activation('relu'))
model1.add(MaxPooling2D(pool_size=(2, 2)))

model1.add(Conv2D(64, (3, 3), activation='relu'))
model1.add(MaxPooling2D(pool_size=(2, 2)))

model1.add(Flatten())
model1.add(Dense(16))
model1.add(Dense(3, activation='softmax'))

model1.summary()

model1.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

history = model1.fit(X_train_sampled[:300], y_train_sampled[:300], batch_size=8, epochs=10, validation_data=(X_test[:75], y_test[:75]))

"""# Results"""

plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()
plt.show()

y_pred = model1.predict(X_test[:100], verbose=1)
y_pred_bool = np.argmax(y_pred, axis=1)

print(classification_report(y_test[:100], y_pred_bool))

cmf=confusion_matrix(y_true=y_test[:100], y_pred=y_pred_bool)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, roc_auc_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

y_test_one_hot = label_binarize(y_test[:100], classes=[0, 1, 2])
y_pred_one_hot = label_binarize(y_pred_bool, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_one_hot, y_pred_one_hot, average='macro')
mae=mean_absolute_error(y_test[:100], y_pred_bool)
mse=mean_squared_error(y_test[:100], y_pred_bool)
r2=r2_score(y_test[:100], y_pred_bool)
accuracy = accuracy_score(y_test[:100], y_pred_bool)
recall = recall_score(y_test[:100], y_pred_bool, average='weighted')
precision = precision_score(y_test[:100], y_pred_bool, average='weighted')
f1s = f1_score(y_test[:100], y_pred_bool, average='weighted')

print("Accuracy: "+ "{}".format(accuracy))
print("Recall: "+ "{}".format(recall))
print("Precision: "+ "{}".format(precision))
print("F1-Score: "+ "{}".format(f1s))
print("Mean Square Error: "+ "{}".format(mse))
print("Mean Abslute Error: "+ "{}".format(mae))
print("R2 Score: "+ "{}".format(r2))
print("ROC-AUC: "+ "{}".format(roc_auc))
model_performance.loc['FT_CNN'] = [accuracy, recall, precision, f1s,mse,mae,r2,roc_auc]

# Plot ROC curve
fpr = dict()
tpr = dict()
roc_auc_values = dict()

for i in range(3):  # Assuming 3 classes, adjust accordingly
    fpr[i], tpr[i], _ = roc_curve(y_test_one_hot[:, i], y_pred_one_hot[:, i])
    roc_auc_values[i] = roc_auc_score(y_test_one_hot[:, i], y_pred_one_hot[:, i])

# Plot ROC curve for each class
plt.figure(figsize=(8, 6))

for i in range(3):  # Assuming 3 classes, adjust accordingly
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc_values[i]:.2f})')

plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for CL-PSO with VGGNet16 Model')
plt.legend()
plt.show()

import seaborn as sns
sns.heatmap(cmf, annot=True)

model_performance.sort_values(by='Accuracy', ascending=False).style.background_gradient(
        cmap='coolwarm').set_properties(**{
            'font-family': 'Lucida Calligraphy',
            'color': 'LigntGreen',
            'font-size': '15px'
        })

